version: '3.8'

services:
  crm-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-ui
    ports:
      - "8080:80"
    networks:
      - crm-network

networks:
  crm-network:
    external: true
